# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Valarie Martin Stuart
email: valariestuart@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a user experience and interface designer who loves clean design,
  typographical hierarchies, logical layouts, and happy users.
url: "localhost:4000" #"http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: valariems
github_username:  valariems
dribbble_username: valariems
linkedin_username: valariems

# Build settings
markdown: kramdown
